version: '3.4'
services:
  express-api-es6-starter:
    build:
      context: .
      target: dev
    volumes:
      - .env.docker:/app/.env
    ports:
      - '8848:8848'
  migration:
    build:
      context: .
      target: migrate
    volumes:
      - .env.docker:/app/.env